services:
  app-frontend:
    build: ../app-frontend
    ports: 
      - 4200:4200
    container_name: app-frontend
    depends_on:
      - app-service

  app-service:
    build: ../app-service
    ports:
      - 8080:8080
    environment:
      - MODEL_SERVICE_URL=http://model-service:8081
    container_name: app-service
    secrets:
      - auth_token

  model-service:
    build: 
      context: ../model-service
      args:
        VERSION: "v0.1.0"
        MODE: PROD
    ports:
      - 8081:8081
    container_name: model-service
    secrets:
      - auth_token

secrets:
  auth_token:
    file: ./auth_token.txt
