services:
  app-frontend:
    image: ghcr.io/remla25-team13/app-frontend:latest
    ports: 
      - 4200:80
    container_name: app-frontend
    restart: on-failure
    depends_on:
      - app-service

  app-service:
    image: ghcr.io/remla25-team13/app-service:latest
    ports: 
      - 8080:5000
    environment:
      - MODEL_TYPE=gauss
      - GDRIVE_CREDENTIALS_DATA=${GDRIVE_CREDENTIALS}
      - MODEL_SERVICE_URL=http://model-service:${MODEL_SERVICE_PORT}
    container_name: app-service
    restart: on-failure
    depends_on:
      - model-service
    secrets:
      - auth_token

  model-service:
    image: ghcr.io/remla25-team13/model-service:latest
    environment:
      - VERSION=v2.0.0
      - ARTIFACT_VERSION=v1.3.3
      - MODE=PROD
      - PORT=${MODEL_SERVICE_PORT}
    ports:
    - "${MODEL_SERVICE_PORT}:${MODEL_SERVICE_PORT}"
    container_name: model-service
    restart: on-failure
    secrets:
      - auth_token
    volumes:
      - ./ml-models-docker:/root/output

secrets:
  auth_token:
    file: ./auth_token.txt
