services:
  app-frontend:
    image: ghcr.io/remla25-team13/app-frontend:latest
    ports: 
      - 4200:4200
    container_name: app-frontend

  app-service:
    image: ghcr.io/remla25-team13/app-service:latest
    ports:
      - 8080:8080
    environment:
      - MODEL_SERVICE_URL=http://model-service:8081
    container_name: app-service

  model-service:
    image: ghcr.io/remla25-team13/model-service:latest
    ports:
      - 8081:8081
    environment:
      - VERSION=v0.1.0
      - MODE=PROD
    container_name: model-service