services:
  app-frontend:
    build: ../app-frontend
    ports: 
      - 4200:4200
  app-service:
    build: ../app-service
    ports:
      - 8080:8080
    environment:
      - MODEL_SERVICE_URL=http://model-service:8081
  model-service:
    build: 
      context: ../model-service
      args:
        VERSION: "v0.1.0"
        MODE: PROD
    ports:
      - 8081:8081