serviceMonitors:
  enabled: true
  additionalServiceMonitors:
    - name: app-service-monitor
      selector:
        matchLabels:
          app: app-service
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: http
          path: /metrics
          interval: 15s
