appFrontend:
  image: ghcr.io/remla25-team13/app-frontend:latest
  host: app.local
  port: 80
  replicas: 1

appService:
  image: ghcr.io/remla25-team13/app-service:latest
  servicePort: 80
  #modelServiceUrlGauss: some_hostname
  #modelServiceUrlMulti: some_hostname
  containerPort: 5000
  replicas: 2
  ratelimit:
    submit: 100

modelService:
  image: ghcr.io/remla25-team13/model-service:latest
  port: 80
  version: v1.2.0
  mode: PROD
  replicas: 2
