{
 "title": "Experiment dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Accuracy over time for both models",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "group by(model_type) (accuracy)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Prediction totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Correct predictions ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(model_type) (correct_pred_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wrong prediction total over time for both models",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(model_type) (wrong_pred_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}