{
 "title": "Team 13 template Copy",
 "time": { "from": "2025-06-26T13:22:13.496Z", "to": "2025-06-26T17:09:53.726Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Correct reviews total",
   "type": "stat",
   "description": "Total amount of correct reviews",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "correct_pred_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last requst time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_req_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sum total correct predictions over all models",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(correct_pred_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Review submission rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 7 },
   "targets": [
    { "expr": "accuracy", "legendFormat": "__auto" }
   ]
  }
 ]
}