- hosts: all
  become: true
  tasks:
    - name: Init cluster
      ansible.builtin.shell:
        cmd: kubeadm init --apiserver-advertise-address=192.168.56.100 --node-name ctrl --pod-network-cidr=10.244.0.0/16

    - name: Create directory for vagrant user
      ansible.builtin.file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy admin.conf
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Download Flannel
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/flannel-io/flannel/v0.26.7/Documentation/kube-flannel.yml
        dest: /home/vagrant/kube-flannel.yml

    - name: Patch Flannel
      ansible.builtin.replace:
        path: /home/vagrant/kube-flannel.yml
        regexp: '(\s*)- --ip-masq'
        replace: '\1- --iface=eth1\n\1- --ip-masq'

    - name: Apply Flannel 
      ansible.builtin.shell:
        cmd: kubectl apply -f /home/vagrant/kube-flannel.yml --kubeconfig=/home/vagrant/.kube/config
        
    - name: add helm key
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        keyring: /etc/apt/keyrings/helm.gpg
        state: present

    - name: Kubernetes to list
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
        state: present
        update_cache: true

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - helm

