- name: general playbook
  hosts: all
  become: yes # makes root
  tasks:  
  - name: Set up multiple authorized keys
    ansible.posix.authorized_key:
      user: vagrant
      state: present
      key: '{{ item }}'
    with_file:
    - ./public_keys/gopal_id_ed25519.pub

  - name: turn off swap
    ansible.builtin.shell:
      cmd: swapoff -a

  - name: comment out swap line
    ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: '.*/swap.*'
      state: absent

  - name: create k8conf
    ansible.builtin.copy:
      content: ""
      dest: /etc/modules-load.d/k8s.conf
      
  - name: configure modules
    ansible.builtin.blockinfile:
      path: /etc/modules-load.d/k8s.conf
      block: |
        overlay
        br_netfilter

  - name: Load br_netfilter
    ansible.builtin.modprobe:
      name: br_netfilter
      state: present

  - name: Load overlay
    ansible.builtin.modprobe:
      name: overlay
      state: present

    # Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  - name: set ip forwarding
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: true
      state: present
      reload: true

  - name: set bridge call ip tables
    ansible.posix.sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
      sysctl_set: true
      state: present
      reload: true

  - name: set bridge call ip6 tables
    ansible.posix.sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
      sysctl_set: true
      state: present
      reload: true

  - name: set host IPs
    ansible.builtin.copy:
      src: hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'

  - name: add kubernetes key
    ansible.builtin.apt_key:
      url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
      keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      state: present

  - name: Kubernetes to list
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /
      state: present

  
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - containerd=1.7.24
      - runc=1.1.12
      - kubeadm = 1.32.4
      - kubelet = 1.32.4
      - kubectl = 1.32.4
