- name: general playbook
  hosts: all
  become: yes # makes root
  tasks:  
    #- name: Set authorized key taken from file
    # ansible.posix.authorized_key:
    #  user: vagrant
    #  state: present
    #  key: "{{ lookup('file', '/home/gopal/.ssh/id_ed25519.pub') }}
  - name: Set up multiple authorized keys
    ansible.posix.authorized_key:
      user: vagrant
      state: present
      key: '{{ item }}'
    with_file:
    - ./public_keys/gopal_id_ed25519.pub

  - name: turn off swap
    ansible.builtin.shell:
      cmd: swapoff -a

  - name: comment out swap line
    ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: '.*/swap.*'
      state: absent

  - name: create k8conf
    ansible.builtin.copy:
      content: ""
      dest: /etc/modules-load.d/k8s.conf
      
  - name: configure modules
    ansible.builtin.blockinfile:
      path: /etc/modules-load.d/k8s.conf
      block: |
        overlay
        br_netfilter

  - name: Load br_netfilter
    ansible.builtin.modprobe:
      name: br_netfilter
      state: present

  - name: Load overlay
    ansible.builtin.modprobe:
      name: overlay
      state: present
