# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.box = "bento/ubuntu-24.04"
    ctrl.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    ctrl.vm.network "private_network", ip: "192.168.56.100"
    ctrl.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
    ctrl.vm.provision :ansible do |acore|
      acore.compatibility_mode = "2.0"
      acore.playbook = "general.yml"
    end
    ctrl.vm.provision :ansible do |acore|
      acore.compatibility_mode = "2.0"
      acore.playbook = "core.yml"
    end
  end

  (1..2).each do |i|
    config.vm.define "node_#{i}" do |n1|
      n1.vm.box = "bento/ubuntu-24.04"
      n1.vm.network "forwarded_port", guest: "8#{i}", host: "808#{i}" , host_ip: "127.0.0.1"
      n1.vm.network "private_network", ip: "192.168.56.10#{i}"
      n1.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 1
      end
      n1.vm.provision :ansible do |anode|
        anode.compatibility_mode = "2.0"
        anode.playbook = "general.yml"
        #anode.playbook = "node.yml"
      end
    end
  end
end
