- name: Finalizing the Cluster Setup
  hosts: all
  environment:
    KUBECONFIG: /home/vagrant/.kube/config
  become: true
  tasks:
    # Step 20: Install MetalLB
    - name: Download MetalLB yaml file
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        dest: "/tmp/metallb-native.yaml"

    - name: Apply metallb-native.yaml
      kubernetes.core.k8s:
        state: present
        src: "/tmp/metallb-native.yaml"

    - name: Create MetalLB IPAddressPool manifest
      copy:
        dest: /tmp/metallb-ipaddresspool.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-pool
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.56.90-192.168.56.99

    - name: Wait for MetalLB controller pod to become ready
      shell: |
        kubectl wait --for=condition=Available deployment -l component=controller -n metallb-system --timeout=300s
      register: metallb_controller_wait
      failed_when: metallb_controller_wait.rc != 0

    - name: Apply metallb-pool.yaml
      kubernetes.core.k8s:
        state: present
        src: "/tmp/metallb-ipaddresspool.yaml"

    - name: Create MetalLB L2Advertisement manifest
      copy:
        dest: /tmp/metallb-l2advertisement.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-advertisement
            namespace: metallb-system
          spec:
            ipAddressPools:
              - default-pool

    - name: Apply metallb-l2advertisement.yaml
      kubernetes.core.k8s:
        state: present
        src: "/tmp/metallb-l2advertisement.yaml"

    # Step 21: Install NGINX Ingress Controller
    - name: Add ingress-nginx Helm repository
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx

    - name: Install ingress-nginx Helm chart
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        release_state: present
        values:
          controller:
            service:
              loadBalancerIP: "192.168.56.90"


    # Step 22: Install Kubernetes Dashboard
    - name: Add kubernetes-dashboard Helm repository
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard/
        state: present

    - name: Install kubernetes-dashboard Helm chart
      kubernetes.core.helm:
        name: kubernetes-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true
        release_state: present

    - name: Copy dashboard-admin-user.yaml to VM
      copy:
        src: files/dashboard-admin-user.yaml
        dest: /tmp/dashboard-admin-user.yaml

    - name: Create admin user
      kubernetes.core.k8s:
        state: present
        src: "/tmp/dashboard-admin-user.yaml"

    - name: Copy dashboard-ingress.yaml to VM
      copy:
        src: files/dashboard-ingress.yaml
        dest: /tmp/dashboard-ingress.yaml

    - name: Wait for NGINX ingress controller to become ready
      shell: |
        kubectl wait --namespace ingress-nginx \
          --all \
          --for=condition=Ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=90s
      register: nginx_wait_result
      failed_when: nginx_wait_result.rc != 0

    - name: Apply dashboard-ingress.yaml
      kubernetes.core.k8s:
        state: present
        src: "/tmp/dashboard-ingress.yaml"

    - name: Add Prometheus repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Copy monitoring values to remote machine
      ansible.builtin.copy:
        src: files/monitoring-values.yaml
        dest: /tmp/monitoring-values.yaml

    - name: Install kube-prometheus-stack (Prometheus-Operator + Grafana)
      kubernetes.core.helm:
        name: monitoring
        chart_ref: prometheus-community/kube-prometheus-stack
        namespace: monitoring
        create_namespace: true
        update_repo_cache: true
        release_state: present
        values_files:
          - /tmp/monitoring-values.yaml
        

    # Step 23: Install Istio
    - name: Download Istio-1.25.2 and unpack it
      ansible.builtin.unarchive:
        src: https://github.com/istio/istio/releases/download/1.25.2/istio-1.25.2-linux-amd64.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    - name: Add the istioctl binary to the PATH variable
      ansible.builtin.copy:
        src: /usr/local/bin/istio-1.25.2/bin/istioctl
        dest: /usr/local/bin/istioctl
        remote_src: yes
        mode: "0755"

    - name: IstioOperator
      ansible.builtin.copy:
        content: |
          apiVersion: install.istio.io/v1alpha1
          kind: IstioOperator
          spec:
            components:
              ingressGateways:
              - name: istio-ingressgateway
                enabled: true
                k8s:
                  service:
                    loadBalancerIP: 192.168.56.91
        dest: config.yml

    - name: Install Istio
      ansible.builtin.shell: istioctl install -y -f config.yml

    - name: Enable Istio
      ansible.builtin.shell: kubectl label ns default istio-injection=enabled

    - name: Wait for Istio ingress gateway to become ready
      shell: |
        kubectl wait --namespace istio-system --for=condition=Available deployment istio-ingress-gateway --timeout=300s
      register: istio_ingress_wait
      failed_when: istio_ingress_wait.rc != 0
