- hosts: workers
  become: true
  tasks:
    - name: Generate join command on controller (delegated task)
      command: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl # Runs this on the controller node instead of workers
      run_once: true # Only need to run this once for all workers

    - name: Wait for the communication from control to node to be established
      delegate_to: ctrl
      shell: |
        ping -c 1 -W 1 {{ inventory_hostname }} > /dev/null 2>&1
      register: ping_result
      until: ping_result.rc == 0
      retries: 300
      delay: 0

    - name: Join worker node to Kubernetes cluster
      shell: "{{ join_command.stdout }}"

    - name: Check if kubernetes config already exists
      stat:
        path: /home/vagrant/.kube
      register: kubeconfig_exists

    - name: Create .kube directory for vagrant user
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: "0755"
      when: not kubeconfig_exists.stat.exists

    - name: Copy kubeconfig to worker node
      copy:
        src: /etc/kubernetes/kubelet.conf
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: "0644"
        remote_src: yes
