- name: Istio Rate Limiting Setup
  hosts: all
  become: true
  vars:
    service_name: model-service 
    namespace: default

  tasks:
    - name: Apply rate limit service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'https://raw.githubusercontent.com/istio/istio/release-1.20/samples/ratelimit/rate-limit-service.yaml') }}"

    - name: Create EnvoyFilter for rate limiting
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.istio.io/v1alpha3
          kind: EnvoyFilter
          metadata:
            name: rate-limit
            namespace: istio-system
          spec:
            workloadSelector:
              labels:
                istio: ingressgateway
            configPatches:
              - applyTo: HTTP_FILTER
                match:
                  context: GATEWAY
                  listener:
                    portNumber: 80
                    filterChain:
                      filter:
                        name: envoy.filters.network.http_connection_manager
                        subFilter:
                          name: envoy.filters.http.router
                patch:
                  operation: INSERT_BEFORE
                  value:
                    name: envoy.filters.http.ratelimit
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                      domain: echo-ratelimit
                      failure_mode_deny: true
              - applyTo: CLUSTER
                match:
                  context: ANY
                patch:
                  operation: ADD
                  value:
                    name: rate_limit_cluster
                    type: STRICT_DNS
                    connect_timeout: 0.25s
                    lb_policy: ROUND_ROBIN
                    load_assignment:
                      cluster_name: rate_limit_cluster
                      endpoints:
                        - lb_endpoints:
                            - endpoint:
                                address:
                                  socket_address:
                                    address: rate-limit
                                    port_value: 8081

    - name: Apply QuotaSpec and QuotaSpecBinding
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: List
          items:
            - apiVersion: ratelimit.istio.io/v1alpha1
              kind: QuotaSpec
              metadata:
                name: request-count
                namespace: "{{ namespace }}"
              spec:
                rules:
                  - quotas:
                      - charge: 1
                        quota: requestcount
            - apiVersion: ratelimit.istio.io/v1alpha1
              kind: QuotaSpecBinding
              metadata:
                name: bind-request-count
                namespace: "{{ namespace }}"
              spec:
                quotaSpecs:
                  - name: request-count
                    namespace: "{{ namespace }}"
                services:
                  - name: "{{ service_name }}"
                    namespace: "{{ namespace }}"

    - name: Restart Istio ingress gateway
      ansible.builtin.command: kubectl rollout restart deployment istio-ingressgateway -n istio-system
