apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-rules
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
  - name: {{ include "sentiment-chart.name" . }}-general-rules
    rules:
    - alert: IncreasedRateOfSlowRequests
      expr: sum(rate(flask_http_request_duration_seconds_bucket{le="+Inf"}[5m])) by (job) - sum(rate(flask_http_request_duration_seconds_bucket{le="2"}[5m])) by (job) / avg_over_time((sum(rate(flask_http_request_duration_seconds_bucket{le="+Inf"}[5m])) by (job) - sum(rate(flask_http_request_duration_seconds_bucket{le="2"}[5m])) by (job))[1h:5m]) > 1.5
      for: 1m
      labels:
        severity: warning
        app: {{ include "sentiment-chart.name" . }}

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ include "sentiment-chart.name" . }}-alertmanager-config
  labels:
    alertmanagerConfig: {{ include "sentiment-chart.name" . }}-alertmanager-config
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'webhook'
  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'https://rstular.eu/webhookingress/remla-alerting'
