apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-config
data:
  MODEL_SERVICE_URL_A: {{ .Values.appService.modelServiceUrlGauss | quote }}
  MODEL_SERVICE_URL_B: {{ .Values.appService.modelServiceUrlMulti | quote }}