---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-app-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-app-frontend
    spec:
      containers:
      - name: {{ .Values.prefix }}-app-frontend
        image: {{ .Values.appFrontend.image }}
        ports:
        - containerPort: {{ .Values.appFrontend.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-app-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-app-service
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-app-service
        version: v1
    spec:
      containers:
      - name: {{ .Values.prefix }}-app-service
        image: {{ .Values.appService.image }}
        env:
        - name: MODEL_SERVICE_URL_A
          value: {{ .Values.appService.modelServiceUrlA }}
        - name: MODEL_SERVICE_URL_B
          value: {{ .Values.appService.modelServiceUrlB }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-app-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-app-service
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-app-service
        version: v2
    spec:
      containers:
      - name: {{ .Values.prefix }}-app-service
        image: {{ .Values.appService.image }}
        env:
        - name: MODEL_SERVICE_URL_A
          value: {{ .Values.appService.modelServiceUrlA }}
        - name: MODEL_SERVICE_URL_B
          value: {{ .Values.appService.modelServiceUrlB }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-model-service-gauss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-model-service
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-model-service
        version: v1
    spec:
      containers:
      - name: {{ .Values.prefix }}-model-service-gauss
        image: {{ .Values.modelService.image }}
        env:
        - name: VERSION
          value: "{{ .Values.modelService.version }}"
        - name: MODE
          value: "{{ .Values.modelService.mode }}"
        - name: PORT
          value: "{{ .Values.modelService.portA }}"
        - name: MODEL_TYPE
          value: "gauss"
        ports:
        - containerPort: {{ .Values.modelService.portA }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-model-service-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-model-service
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-model-service
        version: v2
    spec:
      containers:
      - name: {{ .Values.prefix }}-model-service-multi
        image: {{ .Values.modelService.image }}
        env:
        - name: VERSION
          value: "{{ .Values.modelService.version }}"
        - name: MODE
          value: "{{ .Values.modelService.mode }}"
        - name: PORT
          value: "{{ .Values.modelService.portB }}"
        - name: MODEL_TYPE
          value: "multi"
        ports:
        - containerPort: {{ .Values.modelService.portB }}