---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-frontend
spec:
  replicas: {{ .Values.appFrontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-app-frontend
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-app-frontend
    spec:
      containers:
      - name: {{ include "sentiment-chart.fullname" . }}-app-frontend
        image: {{ .Values.appFrontend.image }}
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "sentiment-chart.fullname" . }}-app-frontend-config
              key: apiHost
        ports:
        - containerPort: {{ .Values.appFrontend.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-service-gauss
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-app-service
    version: gauss
spec:
  replicas: {{ .Values.appService.replicas }}
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-app-service
      version: gauss
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-app-service
        version: gauss
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.appService.containerPort }}"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: {{ include "sentiment-chart.fullname" . }}-app-service
        image: {{ .Values.appService.image }}
        ports:
        - containerPort: {{ .Values.appService.containerPort }}
        env:
        - name: MODEL_SERVICE_URL
          value: {{ .Values.appService.modelServiceUrlGauss | default (printf "http://%s-model-service-gauss" (include "sentiment-chart.fullname" .)) }}
        - name: MODEL_TYPE
          value: gauss
        - name: GDRIVE_CREDENTIALS_DATA
          valueFrom:
            secretKeyRef:
              name: {{ include "sentiment-chart.fullname" . }}-gdrive-credentials
              key: token

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-service-multi
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-app-service
    version: multi
spec:
  replicas: {{ .Values.appService.replicas }}
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-app-service
      version: multi
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-app-service
        version: multi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.appService.containerPort }}"
    spec:
      containers:
      - name: {{ include "sentiment-chart.fullname" . }}-app-service
        image: {{ .Values.appService.image }}
        env:
        - name: MODEL_SERVICE_URL
          value: {{ .Values.appService.modelServiceUrlMulti | default (printf "http://%s-model-service-multi" (include "sentiment-chart.fullname" .)) }}
        - name: MODEL_TYPE
          value: multi
        - name: GDRIVE_CREDENTIALS_DATA
          valueFrom:
            secretKeyRef:
              name: {{ include "sentiment-chart.fullname" . }}-gdrive-credentials
              key: token

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-model-service-gauss
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-model-service
    version: gauss
spec:
  replicas: {{ .Values.modelService.replicas }}
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-model-service
      version: gauss
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-model-service
        version: gauss
    spec:
      containers:
      - name: {{ include "sentiment-chart.fullname" . }}-model-service-gauss
        image: {{ .Values.modelService.image }}
        env:
        - name: VERSION
          value: "{{ .Values.modelService.version }}"
        - name: MODE
          value: "{{ .Values.modelService.mode }}"
        - name: PORT
          value: "{{ .Values.modelService.port }}"
        - name: MODEL_TYPE
          value: "gauss"
        ports:
        - containerPort: {{ .Values.modelService.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-model-service-multi
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-model-service
    version: multi
spec:
  replicas: {{ .Values.modelService.replicas }}
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-model-service
      version: multi
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-model-service
        version: multi
    spec:
      containers:
      - name: {{ include "sentiment-chart.fullname" . }}-model-service-multi
        image: {{ .Values.modelService.image }}
        env:
        - name: VERSION
          value: "{{ .Values.modelService.version }}"
        - name: MODE
          value: "{{ .Values.modelService.mode }}"
        - name: PORT
          value: "{{ .Values.modelService.port }}"
        - name: MODEL_TYPE
          value: "multi"
        ports:
        - containerPort: {{ .Values.modelService.port }}
