---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-app-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-app-frontend
    spec:
      containers:
      - name: {{ .Values.prefix }}-app-frontend
        image: {{ .Values.appFrontend.image }}
        env:
        - name: API_HOST
          value: http://{{ .Values.appService.host }}
        ports:
        - containerPort: {{ .Values.appFrontend.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-app-service-gauss
  labels:
    app: {{ .Values.prefix }}-app-service
    version: gauss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-app-service
      version: gauss
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-app-service
        version: gauss
    spec:
      containers:
      - name: {{ .Values.prefix }}-app-service
        image: {{ .Values.appService.image }}
        env:
        - name: MODEL_SERVICE_URL
          value: {{ .Values.appService.modelServiceUrlGauss }}
        - name: MODEL_TYPE
          value: gauss
        - name: GDRIVE_CREDENTIALS_DATA
          valueFrom:
            secretKeyRef:
              name: {{ .Values.prefix }}-gdrive-credentials
              key: token

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-app-service-multi
  labels:
    app: {{ .Values.prefix }}-app-service
    version: multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-app-service
      version: multi
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-app-service
        version: multi
    spec:
      containers:
      - name: {{ .Values.prefix }}-app-service
        image: {{ .Values.appService.image }}
        env:
        - name: MODEL_SERVICE_URL
          value: {{ .Values.appService.modelServiceUrlMulti }}
        - name: MODEL_TYPE
          value: multi
        - name: GDRIVE_CREDENTIALS_DATA
          valueFrom:
            secretKeyRef:
              name: {{ .Values.prefix }}-gdrive-credentials
              key: token

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-model-service-gauss
  labels:
    app: {{ .Values.prefix }}-model-service
    version: gauss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-model-service
      version: gauss
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-model-service
        version: gauss
    spec:
      containers:
      - name: {{ .Values.prefix }}-model-service-gauss
        image: {{ .Values.modelService.image }}
        env:
        - name: VERSION
          value: "{{ .Values.modelService.version }}"
        - name: MODE
          value: "{{ .Values.modelService.mode }}"
        - name: PORT
          value: "{{ .Values.modelService.port }}"
        - name: MODEL_TYPE
          value: "gauss"
        ports:
        - containerPort: {{ .Values.modelService.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-model-service-multi
  labels:
    app: {{ .Values.prefix }}-model-service
    version: multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prefix }}-model-service
      version: multi
  template:
    metadata:
      labels:
        app: {{ .Values.prefix }}-model-service
        version: multi
    spec:
      containers:
      - name: {{ .Values.prefix }}-model-service-multi
        image: {{ .Values.modelService.image }}
        env:
        - name: VERSION
          value: "{{ .Values.modelService.version }}"
        - name: MODE
          value: "{{ .Values.modelService.mode }}"
        - name: PORT
          value: "{{ .Values.modelService.port }}"
        - name: MODEL_TYPE
          value: "multi"
        ports:
        - containerPort: {{ .Values.modelService.port }}