---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-app-frontend
spec:
  selector:
    app: {{ .Values.prefix }}-app-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.appFrontend.port }}
      targetPort: {{ .Values.appFrontend.port }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.appService.containerPort }}"
spec:
  selector:
    app: {{ .Values.prefix }}-app-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.appService.servicePort }}
      targetPort: {{ .Values.appService.containerPort }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-model-service-gauss
spec:
  selector:
    app: {{ .Values.prefix }}-model-service
    version: v1
  ports:
    - protocol: TCP
      port: {{ .Values.modelService.portA }}
      targetPort: {{ .Values.modelService.portA }}
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-model-service-multi
spec:
  selector:
    app: {{ .Values.prefix }}-model-service
    version: v2
  ports:
    - protocol: TCP
      port: {{ .Values.modelService.portB }}
      targetPort: {{ .Values.modelService.portB }}
  type: ClusterIP
