---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-app-frontend
spec:
  selector:
    app: {{ .Values.prefix }}-app-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.appFrontend.port }}
      targetPort: {{ .Values.appFrontend.port }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-app-service
spec:
  selector:
    app: {{ .Values.prefix }}-app-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.appService.servicePort }}
      targetPort: {{ .Values.appService.containerPort }}
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-model-service-gauss
spec:
  selector:
    app: {{ .Values.prefix }}-model-service
    version: gauss
  ports:
    - protocol: TCP
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-model-service-multi
spec:
  selector:
    app: {{ .Values.prefix }}-model-service
    version: multi
  ports:
    - protocol: TCP
      port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.port }}
  type: ClusterIP
