apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-frontend
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingressgateway
  http:
    - route:
        - destination:
            host: app-service
            subset: v1
          weight: 90
        - destination:
            host: app-service
            subset: v2
          weight: 10
      headers:
        request:
          add:
            user: "{% random 1 100 %}"

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-service
spec:
  host: app-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 0s