apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.prefix }}-app-frontend
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.prefix }}-istio-ingressgateway
  http:
    - route:
        - destination:
            host: {{ .Values.prefix }}-app-service
            subset: v1
          weight: 90
        - destination:
            host: {{ .Values.prefix }}-app-service
            subset: v2
          weight: 10

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.prefix }}-app-service
spec:
  host: {{ .Values.prefix }}-app-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 0s