apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.prefix }}-app-service
spec:
  hosts:
    - {{ .Values.appService.host }}
  gateways:
    - {{ .Values.prefix }}-istio-ingressgateway
  http:
    - route:
        - destination:
            host: {{ .Values.prefix }}-app-service
            subset: multi
          weight: 90
        - destination:
            host: {{ .Values.prefix }}-app-service
            subset: gauss
          weight: 10

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.prefix }}-app-service
spec:
  host: {{ .Values.prefix }}-app-service
  subsets:
    - name: multi
      labels:
        version: multi
    - name: gauss
      labels:
        version: gauss
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 0s

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.prefix }}-app-frontend
spec:
  hosts:
    - {{ .Values.appFrontend.host }}
  gateways:
    - {{ .Values.prefix }}-istio-ingressgateway
  http:
    - route:
        - destination:
            host: {{ .Values.prefix }}-app-frontend
